### PR TITLE
Update Postgresql to 13.6

### PR DESCRIPTION
**Pull request by ykgmfq**

### CODE REVIEW

**Comment by jralls** [comment]
Wrong repo. The correct one is [gnucash-on-flatpak](https://github.com/gnucash/gnucash-on-flatpak/).

**Comment by fellen** [comment]
@jralls but the test build here is faster. :-)

**Comment by gjanssens** [comment]
As long as this just is used for test builds I would also be ok with it. We don't provide an easy ourselves to test PRs. So allowing test builds here by using PRs is a fair alternative.

**Comment by jralls** [comment]
It should be possible to set up a test build with github actions, but I don't expect to have time to do so anytime soon.

**Pull request closed without merging**
