### PR TITLE
Update to runtime 3.30, GnuCash 3.4

### LINKED ISSUE #9: 3.0 released
https://lists.gnucash.org/pipermail/gnucash-user/2018-April/075866.html

Big release with things like the gtk3/webkit2 migration.

### LINKED ISSUE #15: Bug URL changed to bugs.gnucash.org
Hi,

because gnome.org had announced to close bugzilla.gnome.org, we have set up our own bugzilla instance at https://bugs.gnucash.org.
Can you adjust your links, please?

Sojurces:
https://lists.gnucash.org/pipermail/gnucash-announce/2018-June/000284.html
https://lists.gnucash.org/pipermail/gnucash-announce/2018-June/000285.html

### LINKED ISSUE #18: version 3.3 is available

### PR DESCRIPTION
**Pull request by ykgmfq**
Resolves #9, resolves #15 and resolves #18

### CODE REVIEW

**Comment by ykgmfq** [comment]
Module gc needs https://github.com/ivmai/libatomic_ops.

**Comment by ykgmfq** [comment]
testbot, build org.gnucash.GnuCash

**Comment by ykgmfq** [comment]
testbot, build org.gnucash.GnuCash

**Comment by ykgmfq** [comment]
@barthalion would you please review this?

**Comment by nedrichards** [comment]
bot, build

**Comment by ykgmfq** [comment]
@barthalion ping

**Comment by gjanssens** [comment]
Thanks for the PR. It appears to work fine and considering it's been lingering for so long I have merged it as is. Meanwhile a few things have moved on:
* Apparently gc 8.x no longer requires libatomic_ops if the compiler has atomic semantics. With your upgrade to the gnome 3.30 sdk, the flatpak is now being built with gcc 8.3 which I believe supports atomic semantics. So in a followup commit I have chosen to just update the gc version to 8.0.4 and remove the libatomic_ops dependency again.
* gnucash is now at 3.6, so I have updated accordingly.

**Pull request merged**
