### PR TITLE
Update to 3.0

### PR DESCRIPTION
**Pull request by barthalion**
Work in progress.

### CODE REVIEW

**Comment by barthalion** [comment]
bot, build

**Comment by barthalion** [comment]
Build for x86_64 will likely fail like this:
```
libtool:   error: cannot find the library '/run/build/aqbanking/src/plugins/backends/aqhbci/plugin/libaqhbci.la' or unhandled argument '/run/build/aqbanking/src/plugins/backends/aqhbci/plugin/libaqhbci.la'
```

But honestly I'm not sure if I know how to fix this.

**Comment by nedrichards** [comment]
yeah, as suspected it fails there: https://flathub.org/builds/#/builders/2/builds/588

interesting! i'll take a look when I can.

**Comment by barthalion** [comment]
Totally plausible it misses boost/etc, but fails earlier than this so decided to push it in current state for now.

**Comment by nedrichards** [comment]
I pushed some updates - still fails in the same place, which is sad - but didn't want the updates lost.

**Comment by nedrichards** [comment]
bot, build

**Comment by barthalion** [comment]
You forgot to commit some files, flatpak-builder complains about missing patch.

**Comment by nedrichards** [comment]
Apologies - will fix that in a second. In the interim going to push a branch for 2.6.21 and include libofx to fix some short term bugs.

**Comment by nedrichards** [comment]
bot, build

**Comment by barthalion** [comment]
bot, build

**Comment by barthalion** [comment]
bot, build

**Comment by nedrichards** [comment]
bot, build

**Comment by barthalion** [comment]
Last thing it needs is adding gtest and gmock + possibly some cleanup for files not needed on runtime.

**Comment by nedrichards** [comment]
bot, build

**Comment by nedrichards** [comment]
Yeah, nice! Cleanup certainly would be appreciated given how many things there are that go into making this.

**Comment by barthalion** [comment]
bot, build

**Comment by barthalion** [comment]
bot, build

**Comment by nedrichards** [comment]
Woo! Just down to making sure the appdata file has the right stuff in it.

**Comment by nedrichards** [comment]
Actually upon looking a bit closer I think this is something that'll be fixed by [flatpak-builder 0.99.1](https://github.com/flatpak/flatpak-builder/releases/tag/0.99.1) https://flathub.org/builds/#/builders/30/builds/316

**Comment by barthalion** [comment]
bot, build

**Pull request merged**
