### PR TITLE
Remove dconf access

### LINKED ISSUE #36: Remove dconf workaround
https://blogs.gnome.org/mclasen/2019/07/12/settings-in-a-sandbox-world/

### PR DESCRIPTION
**Pull request by lionirdeadman**
Fix #36

Includes #42

### CODE REVIEW

**Comment by jralls** [comment]
@lionirdeadman If you rebase it should build OK, but based on the blog article cited in #36 just removing the dconf hole without setting up the migration will lose existing users' preferences. Unfortunately the blog article seems to be mistaken about passing `--metadata` to `flatpak-builder`, there is no such option, and I don't understand where the ``[X-DConf]` tag is supposed to go. Do you?

**Comment by lionirdeadman** [comment]
It's what I added `"--metadata=X-DConf=migrate-path=/org/gnucash/"`. But yes, I guess I'll need to rebase this. Will take a moment to figure out.

**Comment by gjanssens** [comment]
> It's what I added `"--metadata=X-DConf=migrate-path=/org/gnucash/"`. But yes, I guess I'll need to rebase this. Will take a moment to figure out.

That's the proper incantation and I was already testing this a few weeks back. It won't work for gnucash unfortunately. I have detailed the issue [here](https://github.com/flatpak/flatpak/issues/4209#issuecomment-846411021).

In short flatpak refuses to migrate because our preferences path prefix "/org/gnucash" is not "similar" enough to the flatpak app-name "org.gnucash.GnuCash".
The prefix "/org/gnucash" is an unfortunate design decision taken years ago, long before flatpak was invented.

There's no easy fix for this.
Alternatives are:
1. Do nothing, which means  that every user switching from a host gnucash to a flatpak gnucash will loose preferences (some of which will impact data storage). All users upgrading from gnucash 4.4 to 4.5 or more recent will have the  same issue.
2. Change our preferences prefix from "/org/gnucash" to "/org/gnucash/gnucash". Unless combined with some solid migration code, this would mean *every* user will lose their preferences. Solid migration code is not too easy. So this requires a lot of extra work on behalf of the gnucash developers to do this right.
3. Revert back to Gnome Sdk 3.36. That is certainly possible temporary workaround, but not a long term solution.

I had hoped the flatpak community would react faster to my issue.

**Comment by gjanssens** [comment]
Regarding to the flatpak community response it may be the issue is not recognized when scanning issue titles. So I have opened flatpak/flatpak#4333 specifically describing our issue with the path prefix/app-name mismatch.

**Comment by gjanssens** [comment]
We have chosen to move our preferences from org.gnucash to org.gnucash.GnuCash in version 4.7 and have removed the dconf workaround accordingly. This closes #36 .

**Pull request closed without merging**
